#ifndef SCREENS_H
#define SCREENS_H

enum Screen {
  SCREEN_MENU,
  SCREEN_AUTO_WATCH,
  SCREEN_RF_HEALTH,
  SCREEN_MONITOR,
  SCREEN_ANALYZER,
  SCREEN_DEVICE_MONITOR,
  SCREEN_AP_LIST,
  SCREEN_AP_DETAIL,
  SCREEN_AP_WALK_TEST,
  SCREEN_BLE_SCAN,
  SCREEN_BLE_DETAIL,
  SCREEN_BLE_WALK_TEST,
  SCREEN_SECURITY_MENU,
  SCREEN_DEAUTH_WATCH,
  SCREEN_ROGUE_AP_WATCH,
  SCREEN_BLE_TRACKER_WATCH,
  SCREEN_ALERT_SETTINGS,
  SCREEN_INSIGHTS_MENU,
  SCREEN_WHY_IS_IT_SLOW,
  SCREEN_CHANNEL_RECOMMENDATION,
  SCREEN_ENVIRONMENT_CHANGE,
  SCREEN_QUICK_SNAPSHOT,
  SCREEN_CHANNEL_SCORECARD,
  SCREEN_HISTORY_MENU,
  SCREEN_EVENT_LOG,
  SCREEN_BASELINE_COMPARE,
  SCREEN_EXPORT,
  SCREEN_SYSTEM_MENU,
  SCREEN_BATTERY_POWER,
  SCREEN_DISPLAY_SETTINGS,
  SCREEN_RADIO_CONTROL,
  SCREEN_POWER_MODE,
  SCREEN_ABOUT,
  SCREEN_DEVICE_DETAIL,
  SCREEN_COMPARE,
  SCREEN_STATS,
  SCREEN_HIDDEN_SSID
};

extern Screen currentScreen;

#endif // SCREENS_H
